import {
  Accordion,
  AccordionContent,
  Button,
  Spinner,
  Label,
  Select,
} from "flowbite-react";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { FaRegSave } from "react-icons/fa";
import { RiRefreshFill } from "react-icons/ri";
import { useDispatch, useSelector } from "react-redux";
import { getConfig, updateConfig } from "../../../api/configApi";
import { setConfig } from "../../../redux/configSlice";
import CompanyDataSettings from "./CompanyDataSettings";
import PurchaseApprovalSettings from "./PurchaseApprovalSettings";
import { getPagePermission } from "../../../utils/permissionHelper";

import ShadowMultiplierButton from "./components/ShadowMultiplierButton";
import CompareRetailerMultiplierButton from "./components/CompareRetailerMultiplierButton";

export const Settings = () => {
  const dispatch = useDispatch();
  const currentUser = useSelector((state) => state?.user?.userInfo);
  const role = currentUser?.role?.toLowerCase();

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [formData, setFormData] = useState({
    commonSettings: {
      companyName: "",
      companyLogo: "",
    },
    functionalSettings: {
      need_employee_approval_for_po: "admin approval",
      dms_edit_mode_enabled: false,
    },
    centralPortalSettings: {},
    dmsSettings: {},
    autogeneratedCodePrefixSettings: {},
    centralPortalThemeSettings: {},
    dmsThemeSettings: {},
  });

  const permissionState = useSelector((state) => state.permission);
  const [pagePermission, setPagePermission] = useState(null);

  useEffect(() => {
    if (!permissionState?.data?.data) return;

    const permission = getPagePermission(permissionState, "settings-configs");

    setPagePermission(permission);
  }, [permissionState]);

  // Fetch configuration data on component mount
  useEffect(() => {
    fetchConfig();
  }, []);
  const fetchConfig = async () => {
    setLoading(true);
    try {
      const response = await getConfig();
      if (response.data.status === 200) {
        setFormData(response.data.data);
      }
    } catch (error) {
      console.error("Error fetching config:", error);
      toast.error("Failed to load settings");
    } finally {
      setLoading(false);
    }
  };
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    // Handle nested properties with dot notation (e.g., 'commonSettings.companyName')
    if (name.includes(".")) {
      const [category, field] = name.split(".");
      setFormData({
        ...formData,
        [category]: {
          ...formData[category],
          [field]: type === "checkbox" ? checked : value,
        },
      });
    } else {
      // Handle top-level properties (if any)
      setFormData({
        ...formData,
        [name]: type === "checkbox" ? checked : value,
      });
    }
  };
  const handleSave = async () => {
    setSaving(true);
    try {
      const response = await updateConfig(formData);
      if (response.data.status === 200) {
        toast.success("Settings updated successfully");
        setFormData(response.data.data);
        dispatch(setConfig(response.data.data));
      }
    } catch (error) {
      console.error("Error updating config:", error);
      toast.error("Failed to update settings");
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <Spinner size="xl" />
      </div>
    );
  }

  console.log(formData, "formData");

  return (
    <div>
      {pagePermission?.view ? (
        <div className="p-4">
          <div className="flex justify-between items-center mb-4">
            <h1 className="text-2xl font-bold dark:text-white">
              System Settings
            </h1>
            <div className="flex gap-2">
              {role === "admin" && (
                <>
                  {" "}
                  <ShadowMultiplierButton />
                  <CompareRetailerMultiplierButton />
                </>
              )}
              <Button
                color="light"
                onClick={fetchConfig}
                disabled={loading}
                title="Refresh"
              >
                <RiRefreshFill size={20} />
              </Button>
              {pagePermission?.update && (
                <Button
                  color="success"
                  onClick={handleSave}
                  disabled={saving}
                  title="Save"
                >
                  <FaRegSave className="mr-2" />
                  {saving ? "Saving..." : "Save Changes"}
                </Button>
              )}
            </div>
          </div>{" "}
          <div className="grid grid-cols-1 gap-4">
            <Accordion collapseAll={false}>
              {/* Common Settings */}
              <Accordion.Panel>
                <Accordion.Title>Company Info Settings</Accordion.Title>
                <Accordion.Content>
                  <CompanyDataSettings
                    formData={formData}
                    setFormData={setFormData}
                    handleChange={handleChange}
                  />
                </Accordion.Content>
              </Accordion.Panel>

              {/* Functional Settings */}
              <Accordion.Panel>
                <Accordion.Title>Features Settings</Accordion.Title>
                <Accordion.Content>
                  <PurchaseApprovalSettings
                    formData={formData}
                    setFormData={setFormData}
                  />
                </Accordion.Content>
              </Accordion.Panel>

              <Accordion.Panel>
                <Accordion.Title>DMS Setting</Accordion.Title>
                <AccordionContent>
                  <div className="flex items-center justify-between p-2">
                    <div>
                      <h3 className="text-base font-semibold dark:text-white">
                        DMS Transaction Edit Mode
                      </h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        When enabled, the edit button will be visible on DMS
                        transactions
                      </p>
                    </div>
                    <label className="relative inline-flex items-center cursor-pointer">
                      <input
                        type="checkbox"
                        name="functionalSettings.dms_edit_mode_enabled"
                        checked={
                          formData?.functionalSettings?.dms_edit_mode_enabled ||
                          false
                        }
                        onChange={handleChange}
                        className="sr-only peer"
                      />
                      <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-green-300 dark:peer-focus:ring-green-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-green-500"></div>
                      <span className="ml-3 text-sm font-medium text-gray-700 dark:text-gray-300">
                        {formData?.functionalSettings?.dms_edit_mode_enabled
                          ? "Enabled"
                          : "Disabled"}
                      </span>
                    </label>
                  </div>
                </AccordionContent>
              </Accordion.Panel>
            </Accordion>
          </div>
        </div>
      ) : (
        <div className="flex items-center justify-center h-screen">
          <p className="text-gray-500 dark:text-gray-400">
            You don't have permission to view this page.
          </p>
        </div>
      )}
    </div>
  );
};
